option(WITH_LAZPERF "Build PDAL with support for LAZ compression with LAZPERF" TRUE)
if (WITH_LAZPERF)
    # <Cadcorp>
    find_path(LAZPERF_INCLUDE_DIR NAMES lazperf.hpp)
    find_library(LAZPERF_LIBRARY NAMES zstd)
    include(FindPackageHandleStandardArgs)
    find_package_handle_standard_args(LAZPERF REQUIRED_VARS LAZPERF_LIBRARY LAZPERF_INCLUDE_DIR)
    if (LAZPERF_FOUND)
        set(PDAL_HAVE_LAZPERF 1)
        include_directories(${LAZPERF_INCLUDE_DIR})
        link_libraries(${LAZPERF_LIBRARY})
    else()
        message(FATAL_ERROR "Cadcorp: laz-perf not found")
    endif()
    # find_package(Lazperf)
    # set_package_properties(Lazperf PROPERTIES TYPE OPTIONAL)
    # if (LAZPERF_FOUND)
    #     include_directories(${LAZPERF_INCLUDE_DIR})
    #     set(PDAL_HAVE_LAZPERF 1)
    # endif()
    # </Cadcorp>
endif()
